name: Type check
on: [pull_request]

jobs:

  Tlint:
    name: Running Tlint
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.1'
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: composer install --prefer-dist

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Verificando lint
        run: composer run tlint
